In [3]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
book_id_map = pd.read_csv('../data/book_id_map.csv')
book_titles = pd.read_csv('../data/book_titles.csv')
metadata = pd.read_csv('../data/collaborative_book_metadata.csv')
rating_df = pd.read_csv('../data/collaborative_books_df.csv')
user_id_map = pd.read_csv('../data/user_id_map.csv')

def overview(df, name):
    print('' + name, ':', df.shape[0], 'lignes et', df.shape[1], 'colonnes')
    display(df.head())

overview(book_id_map, 'book_id_map')
overview(book_titles, 'book_titles')
overview(metadata, 'collaborative_book_metadata')
overview(rating_df, 'collaborative_books_df')
overview(user_id_map, 'user_id_map')

book_id_map : 2360650 lignes et 2 colonnes

   book_id_csv   book_id
0            0  34684622
1            1  34536488
2            2  34017076
3            3     71730
4            4  30422361

book_titles : 1447341 lignes et 2 colonnes

                                              title  book_id
0    The Unschooled Wizard Sun Wolf and Starhawk 12  7327624
1                              Best Friends Forever  6066819
2                     The Aeneid for Boys and Girls   287141
3  Alls Fairy in Love and War Avalon Web of Magic 8  6066812
4                               The Devils Notebook   287149

collaborative_book_metadata : 96 lignes et 11 colonnes

,Unnamed: 0,book_id,title,image_url,url,num_pages,ratings_count,description,genre,name,book_id_mapping
0,0,5899779,Pride and Prejudice and Zombies Pride and Prej...,https://images.gr-assets.com/books/1320449653m...,https://www.goodreads.com/book/show/5899779-pr...,320,105537,The New York Times Best Seller is now a major ...,"['fantasy, paranormal', 'romance', 'fiction', ...",Jane Austen,808
1,1,872333,Blue Bloods Blue Bloods 1,https://images.gr-assets.com/books/1322281515m...,https://www.goodreads.com/book/show/872333.Blu...,302,117633,"When the Mayflower set sail in 1620, it carrie...","['young-adult', 'fantasy, paranormal', 'romanc...",Melissa de la Cruz,217
2,2,15507958,Me Before You Me Before You 1,https://images.gr-assets.com/books/1357108762m...,https://www.goodreads.com/book/show/15507958-m...,369,609327,Louisa Clark is an ordinary young woman living...,"['romance', 'fiction']",Jojo Moyes,385
3,3,66559,Sharp Objects,https://images.gr-assets.com/books/1423241485m...,https://www.goodreads.com/book/show/66559.Shar...,254,208394,"Fresh from a brief stay at a psych hospital, r...","['mystery, thriller, crime', 'fiction']",Gillian Flynn,192
4,4,7235533,The Way of Kings The Stormlight Archive 1,https://images.gr-assets.com/books/1507307887m...,https://www.goodreads.com/book/show/7235533-th...,1007,151473,"Speak again the ancient oaths,\nLife before de...","['fantasy, paranormal', 'fiction']",Brandon Sanderson,873

collaborative_books_df : 196296 lignes et 7 colonnes

,Unnamed: 0,title,book_id,user_id_mapping,book_id_mapping,Predicted Rating,Actual Rating
0,0,I Am the Messenger,19057,1537,299,4.5,5
1,1,I Am the Messenger,19057,23039,299,4.9,3
2,2,I Am the Messenger,19057,39096,299,3.9,3
3,3,I Am the Messenger,19057,14631,299,4.7,4
4,4,I Am the Messenger,19057,32816,299,4.3,5

user_id_map : 876145 lignes et 2 colonnes

   user_id_csv                           user_id
0            0  8842281e1d1347389f2ab93d60773d4d
1            1  72fb0d0087d28c832f15776b0d936598
2            2  ab2923b738ea3082f5f3efcbbfacb218
3            3  d986f354a045ffb91234e4af4d1b12fd
4            4  7504b2aee1ecb5b2872d3da381c6c91e